services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
